# This is a basic workflow to help you get started with Actions

name: retrieve

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
           - 'force-app/**'
  pull_request:
    branches: [ main ]
    paths:
           - 'force-app/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ Github.ref }}
          fetch-depth: 0
        if: Github.event.action =='opend' || Github.event.action =='synchronize' || Github.event_name == 'push'
      - uses: actions/setup-node@v1
        with:
          node-version: '>=14'
          check-latest: true
        
      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli
          node_modules/sfdx-cli/bin/run --version
          node_modules/sfdx-cli/bin run plugins --core
      
      - name: 'SFDX_AUTH_URLをSFDX_AUTH_URL_FILEファイルに保存'
        shell: bash
        run : 'echo ${{  secrets.SFDX_AUTH_URL }} > SFDX_AUTH_URL_FILE'

      - name: 'Authenticate against dec hub'
        run: node_modules/sfdx-cli/bin/run force:auth:sfdxurl:store -f SFDX_AUTH_URL_FILE -s -a MYDEV

      - name: 'retrieve devhub'
      
      - name: 'commit meta'